import argparse,json,hashlib,subprocess,shutil
from pathlib import Path
p=Path(__file__).resolve().parent;repo=Path('/home/liyufeng/safeduo-dashboard-benchmark-protocol-20261006');pa=argparse.ArgumentParser();pa.add_argument('--archive-commit',required=True);a=pa.parse_args();sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();s=json.loads((p/'SUMMARY.json').read_text());fresh=s['runs']['fresh_scene_batch']['methods']['scene_v4'];matched=s['runs']['matched_scene']['methods'];doc=repo/'docs'/p.name;doc.mkdir(exist_ok=True)
for fn in ['index.html','panel.js']:shutil.copy2(p/'panel'/fn,doc/fn)
shutil.copy2(p/'SUMMARY.json',doc/'SUMMARY.json');base=f'https://raw.githubusercontent.com/asimfish/safeduo-dashboard/{a.archive_commit}/{p.name}/';(doc/'MEDIA_ARCHIVE.json').write_text(json.dumps(dict(commit=a.archive_commit,base=base,manifest_url=base+'MEDIA_MANIFEST.json'),indent=2)+'\n')
manifest=json.loads((p/'MEDIA_MANIFEST.json').read_text());(doc/'PUBLIC_MANIFEST.json').write_text(json.dumps(dict(scope='Limited static four-arm configuration and two U-hand empty closure; full System0 acceptance false.',archive_commit=a.archive_commit,archive_manifest_sha256=sha(p/'MEDIA_MANIFEST.json'),archive_files=manifest['count'],archive_bytes=manifest['bytes'],files=[dict(file=fn,sha256=sha(doc/fn),bytes=(doc/fn).stat().st_size) for fn in ['index.html','panel.js','SUMMARY.json','MEDIA_ARCHIVE.json']]),indent=2)+'\n')
base_commit=json.loads((p/'MAIN_BASE.json').read_text())['commit'];root=repo/'index.html';original=subprocess.check_output(['git','show',base_commit+':index.html'],cwd=repo);current=root.read_bytes();marker=b'<section class="sci-note" id="handClosureEvidence">';assert original.count(marker)==1
card=f'''<section class="sci-note" id="sceneGeometryEvidence"><h2>补充：动作前手部几何准入与24姿态验证</h2><p>新机制读取实际碰撞尺寸与关节运动学，闭合前检查整条手部路径、工装与对侧手扫掠范围；仍保留原生逐点接触监测及锁存退回。</p><p>24个封存新轨迹姿态 × 12个冻结目标 × 两U手，共576请求：{fresh['executed_qualified']}/{fresh['admitted']}准入路径合格，{fresh['refused']}次拒绝，{fresh['aborts']}次中止；其中非中性动作执行合格{fresh['moving_executed_qualified']}条，中性目标准入{fresh['no_motion_admitted']}条。拒绝不计作完成。</p><p>四组同初态旧V3/新几何对照：旧策略中止{matched['old_v3']['aborts']}次，新策略中止{matched['scene_v4']['aborts']}次。完整曲线、六路视频、俯视/正视/侧视/近景与全部路径账本可复核；两路俯视对照及一条右手闭合为标注的存档状态重渲染。</p><p>{s['total_native_env_states']}个完整原生环境状态，{s['original_native_images']}张直接截图；保留中断与初始化失败，不增加独立样本数。此轮仅固定四臂姿态下两U手空手闭合，未验收完整System0协同任务、真实夹持带载释放或全26自由度操作空间。</p><p><a href="docs/{p.name}/">查看新机制、对照视频和完整验收 →</a></p></section>\n'''.encode()
expected=original.replace(marker,card+marker,1);assert current in [original,expected],('unexpected root edits',root);root.write_bytes(expected);assert root.read_bytes().replace(card,b'',1)==original
size=sum(int(line.split()[3]) for line in subprocess.check_output(['git','ls-tree','-rl','HEAD'],cwd=repo,text=True).splitlines() if line.split()[3]!='-')+sum(f.stat().st_size for f in doc.iterdir())+len(card);assert size<1024**3,('main_payload',size)
(p/'MAIN_PAYLOAD_GATE.json').write_text(json.dumps(dict(status='PASS_SMALL_MAIN_PAYLOAD_AND_OLD_ROOT_PRESERVED',payload_bytes=size,cap_bytes=1024**3,new_card_bytes=len(card),old_root_sha256=hashlib.sha256(original).hexdigest(),new_root_sha256=sha(root)),indent=2)+'\n');print(dict(payload_bytes=size,headroom_bytes=1024**3-size,archive_commit=a.archive_commit))
