extends: duo_env_camera_crossrow.yaml
assets:
  table_objects:
  - name: beam_neg
    catalog: beam_50_700
    pos:
    - -0.05
    - -0.3
    - 0.825
    yaw: 90.0
  - name: beam_pos
    catalog: beam_50_700
    pos:
    - -0.05
    - 0.3
    - 0.825
    yaw: 90.0
  - name: obstacle_ur
    size:
    - 0.1
    - 0.1
    - 0.3
    pos:
    - -0.22
    - -0.46
    - 0.95
    mass: 2.0
    color:
    - 0.8
    - 0.15
    - 0.1
