"""Explicit derivation; preserve the sealed v5 recorder byte for byte."""
from pathlib import Path
R=Path(__file__).resolve().parent
OLD=Path('/home/liyufeng/safeduo/artifacts/safety_object_binding_20261006')
s=(OLD/'native_runner_v5.py').read_text()
def replace(old,new):
    global s
    assert s.count(old)==1,old[:100]
    s=s.replace(old,new)
replace('"""Eight prospective native task contrasts with explicit initial object input."""','"""Prospective stationary-release and reactive clearance contrasts."""')
replace("parser.add_argument('--out',type=Path,required=True);AppLauncher.add_app_launcher_args(parser)","parser.add_argument('--out',type=Path,required=True);parser.add_argument('--block',type=int,required=True);AppLauncher.add_app_launcher_args(parser)")
replace("args.out.mkdir(parents=True,exist_ok=False);args.enable_cameras=True", "block=reg['blocks'][args.block];reg['cases']=block['cases'];reg['physics_seed']=block['physics_seed']\nargs.out.mkdir(parents=True,exist_ok=False);args.enable_cameras=True")
replace('from clock_contract import control_clock','from clock_contract import control_clock\nfrom clearance_gate import ClearanceGate,zero_held_command')
replace('n=len(reg[\'cases\']);assert n==8','n=len(reg[\'cases\']);assert n==12')
replace("cfg.coordinator['retreat_dwell_steps']=10;cfg.episode_length_s=40.","cfg.coordinator['retreat_dwell_steps']=10;cfg.episode_length_s=45.")
replace("debt={a:torch.zeros_like(env._targets[a]) for a in ARMS};original_sample=base.sample", "debt={a:torch.zeros_like(env._targets[a]) for a in ARMS};original_sample=base.sample\n    gate=ClearanceGate([c['method'] for c in reg['cases']],dt,reg['gate'],device=env.device)\n    held=torch.zeros(n,dtype=torch.bool,device=env.device);last_gate_input=None")
replace('        return cmd\n    base.sample=sample','        return zero_held_command(cmd,held)\n    base.sample=sample')
replace("source_scope='8-case development contrast; native initial-pose oracle, no vision sensing or online payload correction'", "source_scope='24 development task windows: 4 layouts x 3 methods x 2 seed/slot blocks; original task gates plus explicit abort/completion; no IID or final holdout',block=args.block,static_collision_paths=[str(p.GetPath()) for p in stage.Traverse() if p.HasAPI(UsdPhysics.CollisionAPI) and str(p.GetPath()).startswith('/World/envs/env_0/Prop_')]")
replace("buffers={};chunks=[];images=[]", "buffers={};chunks=[];images=[];video_frames=[];render_checks=[]\n    def fresh_snapshot():\n        return {**{o+':pose':env._objects[o].root_physx_view.get_transforms().detach().clone() for o in OBJECTS},\n            **{o+':velocity':env._objects[o].root_physx_view.get_velocities().detach().clone() for o in OBJECTS},\n            **{a+':q':env._arms[a].root_physx_view.get_dof_positions().detach().clone() for a in ARMS},\n            **{a+':qd':env._arms[a].root_physx_view.get_dof_velocities().detach().clone() for a in ARMS}}\n    def fresh_objects():\n        return torch.stack([torch.cat((env._objects[o].root_physx_view.get_transforms()[:,0:3],env._objects[o].root_physx_view.get_transforms()[:,[6,3,4,5]],env._objects[o].root_physx_view.get_velocities()),-1) for o in OBJECTS],1).detach().clone()")
replace("clock=step*dt;base.set_time((step+1)*dt)", "clock=step*dt;held=gate.step(last_gate_input);base.set_time(gate.phase)\n        # Common harness correction: every method recomputes from the authoritative phase.\n        env._pending_cmd=None")
replace("data=dict(step=np.asarray(step),time=np.asarray([clock,(step+1)*dt]),objects=torch.stack([env._objects[o].data.root_state_w for o in OBJECTS],1),", "data=dict(step=np.asarray(step),time=np.asarray([clock,(step+1)*dt]),objects=fresh_objects(),phase=gate.phase.clone(),gate_stage=gate.stage.clone(),gate_reason=gate.reason.clone(),command_held=held.clone(),")
replace("matrices=[];counts_all=[]", "matrices=[];counts_all=[];nets=[]")
replace("m=[];counts=[]", "m=[];counts=[];net=[]")
replace("assert torch.isfinite(force).all();m.append(force.reshape(len(partners),3));counts.append(cnt.reshape(len(partners)))", "assert torch.isfinite(force).all();m.append(force.reshape(len(partners),3));counts.append(cnt.reshape(len(partners)))\n                net.append(cv.get_net_contact_forces(env.cfg.sim.dt).detach().clone().reshape(3))")
replace("matrices.append(torch.stack(m));counts_all.append(torch.stack(counts))", "matrices.append(torch.stack(m));counts_all.append(torch.stack(counts));nets.append(torch.stack(net))")
replace("data['object_partner_normal']=torch.stack(matrices);data['contact_counts']=torch.stack(counts_all)", "data['object_partner_normal']=torch.stack(matrices);data['contact_counts']=torch.stack(counts_all);data['object_net_contact']=torch.stack(nets)\n        normal=data['object_partner_normal'].norm(dim=-1);states=data['objects'];q=states[:,:,3:7]\n        half=torch.tensor(reg['sizes_m'],device=env.device)*.5\n        qw,qx,qy,qz=q.unbind(-1)\n        rowz=torch.stack((2*(qx*qz-qw*qy),2*(qy*qz+qw*qx),1-2*(qx*qx+qy*qy)),-1)\n        bottom=states[:,:,2]-env.scene.env_origins[:,None,2]-(rowz.abs()*half[None]).sum(-1)\n        last_gate_input=dict(table_n=torch.stack([normal[:,i,next(j for j,p in enumerate(partners) if p.get('table')==t)] for i,t in enumerate(('TableF','TableU'))],-1),\n            bottom_delta_m=bottom-.8,speed_m_s=states[:,:,7:10].norm(dim=-1),angular_rad_s=states[:,:,10:13].norm(dim=-1),\n            tilt_deg=torch.acos(rowz[:,:,2].clamp(-1,1))*180/math.pi,\n            hand_n=torch.stack([torch.stack([normal[:,i,[j for j,p in enumerate(partners) if p['arm']==a and p['hand']]].sum(-1) for a in ARMS[2*i:2*i+2]],-1) for i in range(2)],1),\n            hand_open_max_error_rad=torch.stack([(env._arms[a].root_physx_view.get_dof_positions()[:,hands.ids[a][0]]-hands.open_q[a]).abs().max(-1).values for a in ARMS],-1))\n        for k,v in last_gate_input.items():data['gate_input:'+k]=v\n        data['gate_stable_count']=gate.stable.clone();data['gate_wait_s']=gate.wait.clone()")
replace("if step in capture_steps:\n            before_o=data['objects'].detach().clone();before_q={a:env._arms[a].data.joint_pos.detach().clone() for a in ARMS}\n            selected=list(range(n)) if step==reg['steps']-1 else capture_envs", "video_step=args.block==0 and step in reg['video_steps']\n        if step in capture_steps or video_step:\n            before_o=data['objects'].detach().clone();before_native=fresh_snapshot()\n            selected=list(range(n)) if step in capture_steps else [c['env'] for c in reg['cases'] if c['layout']==0]")
replace("for name,view in reg['views'].items():", "for name,view in reg['views'].items():\n                    if step not in capture_steps and name!='front':continue")
replace("images.append(dict(file=rel,sha256=sha(path),env=e,step=step,state_time_s=(step+1)*dt,view=name,objects=before_o[e].cpu().tolist()))", "item=dict(file=rel,sha256=sha(path),env=e,step=step,state_time_s=(step+1)*dt,view=name,objects=before_o[e].cpu().tolist(),phase_s=float(gate.phase[e]),stage=int(gate.stage[e]))\n                    images.append(item)\n                    if video_step and reg['cases'][e]['layout']==0 and name=='front':video_frames.append(item.copy())")
replace("assert torch.equal(before_o,torch.stack([env._objects[o].data.root_state_w for o in OBJECTS],1))\n            assert all(torch.equal(before_q[a],env._arms[a].data.joint_pos) for a in ARMS)", "after_native=fresh_snapshot()\n            differences={k:float((before_native[k]-after_native[k]).abs().max()) for k in before_native}\n            assert all(v==0 for v in differences.values()),('render mutated physics',step,differences)\n            assert torch.equal(before_o,fresh_objects())\n            render_checks.append(dict(step=step,native_readback_max_abs_differences=differences))")
replace("scope=initial['source_scope'],new_final_trials=0))", "scope=initial['source_scope'],new_final_trials=0,block=args.block,video_frames=video_frames,native_render_checks=render_checks))")
(R/'native_runner.py').write_text(s)
print('Derived native_runner.py with explicit, checked replacements')
