from pathlib import Path
import json
p=Path(__file__).resolve().parent;v=json.loads((p/'VALIDATION_FRESH_V3_FULL_RESULTS.json').read_text());reg=json.loads((p/'VALIDATION_V3_FULL_RESULTS.json').read_text());pair=json.loads((p/'PAIRED_V3_FULL_RESULTS.json').read_text());dev=json.loads((p/'DEVELOPMENT_RESULTS.json').read_text());rec=pair['recoveries'];returned=[x for x in rec if x['method']=='fault_recover'];hold=[x for x in rec if x['method']=='fault_hold']
items=[
 dict(id='A0',criterion='每物理步原生状态、初始有效物理帧、完整性及原图SHA',status='PASS_COMPLETE_RECORDING',evidence=['FINAL_NATIVE_GATE.json','VALIDATION_FRESH_V3_FULL_RESULTS.json','PAIRED_V3_FULL_RESULTS.json']),
 dict(id='A1',criterion='原生资产、自碰开启及对象/手伙伴身份、逐点不抵消法向力',status='PASS_MEASURED_HAND_SCOPE',evidence=['SOURCE_SNAPSHOT.json','SCALAR_NORMAL_CONTRACT.md','VALIDATION_FRESH_V3_FULL_RESULTS.json'],limit='开发仅伙伴向量合力；法向不是完整摩擦wrench。直接6USD指纹封存，嵌套远程材料资产未全部离线封存。'),
 dict(id='A2',criterion='118独特3维目标，完整拇指1/2限位，网格+IID+LHS开发',status='PASS_REGISTERED_EXECUTION_NOT_GLOBAL_SPACE',slots=120,unique_targets=118,native_cycles=360,u_paths=720,qualified_slots_at_all_six_paths=dev['profile_count_qualified'],evidence=['REGISTRATION_DEVELOPMENT.json','DEVELOPMENT_RESULTS.json','COVERAGE_FINAL_REPORT.json']),
 dict(id='A3',criterion='V1初始化失败及V2外部接触失败保留，修复回归',status=reg['status'],executed_qualified=reg['executed_paths_qualified'],executed=reg['executed_requests'],context_refusals=reg['denied_requests'],evidence=['VALIDATION_FULL_RESULTS.json','VALIDATION_V2_EXTERNAL_DIAGNOSTIC.json','SCENE_CONTACT_V3_CONTRACT.md','VALIDATION_V3_FULL_RESULTS.json']),
 dict(id='A4',criterion='12新OS分层姿态×12冻结目标×两U手的新验证',status=v['status'],attempted_paths=v['u_hand_paths'],admitted=v['executed_requests'],executed_qualified=v['executed_paths_qualified'],refused=v['denied_requests'],aborts=v['abort_count'],evidence=['FRESH_EXTENDED_CONTRACT.md','REGISTRATION_VALIDATION_FRESH_V3.json','VALIDATION_FRESH_V3_FULL_RESULTS.json']),
 dict(id='A5',criterion='同初态/目标旧目标执行与拒绝的实际接触对照',status=pair['status'],guard_safe_paths=pair['guard_safe_paths'],guard_paths=pair['guard_paths'],guard_grasp_successes=0,evidence=['REGISTRATION_PAIRED_V3.json','PAIRED_V3_FULL_RESULTS.json','VIDEO_RECEIPT.json']),
 dict(id='A6',criterion='空手工装接触后保持/退回同初态对照',status='PASS_BOUNDED_RECOVERY' if returned and all(x['recovery_s'] is not None and x['last_second_max_n']<=.1 and x['last_second_neutral_error_rad']<=.02 for x in returned) else 'REJECT_OR_UNEXERCISED_RECOVERY',returned=returned,hold=hold,note='第一次接触已违规；退回不保证避免首次冲击，不适用于带载释放。两组使用相同外部接触检测，隔离动作差异。',evidence=['PAIRED_V3_FULL_RESULTS.json','paired_v3/admission_records.json']),
 dict(id='A7',criterion='首次构造内部动力学之前的安全初始化及测力',status='UNVERIFIED',evidence=['BOOTSTRAP_FAILURE_CONTRACT.md'],note='post-write无效接触缓存不是当前物理力证据；构造器内部尚无原生力记录。'),
 dict(id='A8',criterion='真实双手共同物体抓持、搬运阶段持续>50mm抬升及承重/姿态',status='NOT_EXECUTED_NEW_TASK_TRIALS_0',note='物体移远；旧晚期最大抬升不等于真实夹持。旧U目标位置工装承重约69%的失败事实保留。'),
 dict(id='A9',criterion='有效放置支撑、完全回开与安全撤离',status='NOT_EXECUTED_LOADED_RELEASE_TRIALS_0',note='本轮空手回开合格不代表带载释放合格。'),
 dict(id='A10',criterion='六臂对、26臂和48手DOF、感知扰动及全操作空间',status='NOT_COVERED',evidence=['COVERAGE_FINAL_REPORT.json'],note='18个相关静态四臂参考；3维手目标。边缘关节跨度不是高维或世界空间体积覆盖。'),
 dict(id='A11',criterion='纯随机IID物理任务、独立留出与统计安全置信界',status='NOT_ESTABLISHED',note='20 IID开发目标、20分层开发目标；32未知目标只有请求拒绝。12新参考随机时间分层抽样，重复循环/左右手相关，不能作为独立任务分母。'),
 dict(id='A12',criterion='完整媒体SHA下载、页面精确字节、桌面/手机、视频实际播放',status='RECORDED_SEPARATELY_IN_DELIVERY_RECEIPTS',evidence=['MEDIA_MANIFEST.json','ARCHIVE_DOWNLOAD.json','PUBLIC_DELIVERY.json','FINAL_DELIVERY_GATE.json'])]
out=dict(status='COMPREHENSIVE_ROBOT_SAFETY_NOT_QUALIFIED',candidate_status=v['status'],items=items);(p/'ACCEPTANCE_MATRIX.json').write_text(json.dumps(out,indent=2)+'\n');print('ACCEPTANCE_ITEMS',len(items))
