from pathlib import Path
import json,gzip,numpy as np,hashlib
p=Path(__file__).resolve().parent;root=Path('/mnt/nas/data/lyf/double_hand/safety_hand_closure_qualification_20261007');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();data={};gallery=[]
runs=[('development','development','DEVELOPMENT_RESULTS.json'),('validation_v1','validation','VALIDATION_FULL_RESULTS.json'),('validation_v2','validation_v2','VALIDATION_V2_FULL_RESULTS.json'),('validation_v3','validation_v3','VALIDATION_V3_FULL_RESULTS.json'),('validation','validation_fresh_v3','VALIDATION_FRESH_V3_FULL_RESULTS.json'),('paired','paired_v3','PAIRED_V3_FULL_RESULTS.json')]
for key,run,resultname in runs:
 regname='REGISTRATION_'+run.upper()+'.json';r=json.loads((p/regname).read_text());res=json.loads((p/resultname).read_text());raw=root/run;receipt=json.loads((raw/'recording_receipt.json').read_text());meta=json.loads((raw/'native_metadata.json').read_text());identity=json.loads((raw/'contact_identities.json').read_text());curves={}
 for ch in receipt['chunks']:
  with np.load(raw/ch['file']) as z:
   cyc=int(z['cycle'][0]);steps=z['step'];clock=((steps%720)+1)*r['physics_dt_s']
   for e,case in enumerate(r['cases']):
    for arm in ['U_L','U_R']:
     idx=cyc*r['profiles_per_cycle']+case['profile_slot'];ck=(idx,case['reference_time_s'],arm,case.get('method'));c=curves.setdefault(ck,dict(profile_index=idx,reference_time_s=case['reference_time_s'],arm=arm,method=case.get('method'),time_s=[],force=[],all_force=[],q1=[],q2=[],target1=[],target2=[]))
     paths=next(x for x in identity['hands'] if x['env']==e and x['arm']==arm);mask=np.asarray([[x in paths['sensors'] for x in fs] for fs in paths['filters']])
     if run=='development':normal_value=np.linalg.norm(z[f'e{e}:{arm}:hand_partner_normal'],axis=-1)
     else:
      cnt=z[f'e{e}:{arm}:hand_normal_count'];st=z[f'e{e}:{arm}:hand_point_start'];points=z[f'e{e}:{arm}:hand_point_force'];ss=np.where(cnt>0,st,0).astype(int);end=ss+cnt.astype(int);prefix=np.pad(abs(points).astype(np.float64).cumsum(1),((0,0),(1,0)));ix=np.arange(len(points))[:,None,None];normal_value=prefix[ix,end]-prefix[ix,ss]
     force=np.where(mask[None],normal_value,0).max(axis=(1,2));allforce=normal_value.max(axis=(1,2));names=meta['arms'][arm]['joint_names'];ji=[names.index(('left' if arm=='U_L' else 'right')+f'_thumb_{axis}_joint') for axis in [1,2]];q=z[arm+':q'][:,e,ji];tgt=z[arm+':target'][:,e,ji]
     for j in range(0,len(clock),12):
      end=min(j+11,len(clock)-1);c['time_s'].append(float(clock[end]));c['force'].append(float(force[j:end+1].max()));c['all_force'].append(float(allforce[j:end+1].max()));c['q1'].append(float(q[end,0]));c['q2'].append(float(q[end,1]));c['target1'].append(float(tgt[end,0]));c['target2'].append(float(tgt[end,1]))
 frames={}
 for im in receipt['images']:
  step,e=im['step'],im['env'];idx=(step//720)*r['profiles_per_cycle']+r['cases'][e]['profile_slot'];frame=frames.setdefault((step,e),dict(run=run,env=e,method=r['cases'][e].get('method'),profile_index=idx,time_s=im['state_time_s'],step=step,images=[]));frame['images'].append({**im,'file':run+'/'+im['file']})
 gallery.extend(frames.values());display={k:r[k] for k in ['profiles','cases','os_random_seeds','steps','physics_dt_s','scope']};display['os_random_seeds']={k:str(v) for k,v in r['os_random_seeds'].items()}
 data[key]=dict(raw_run=run,registration=display,summary={k:v for k,v in res.items() if k!='rows'},rows=res['rows'],curves=list(curves.values()),normal_metric='vector_resultant' if run=='development' else 'sum_point_normal_magnitudes',results_sha256=sha(p/resultname),registration_sha256=sha(p/regname))
fresh=data['validation']['summary'];reg=data['validation_v3']['summary'];paired=data['paired']['summary'];status=fresh['status']=='PASS_CONDITIONAL_EXECUTIONS_WITH_REFUSALS' and reg['status']=='PASS_CONDITIONAL_EXECUTIONS_WITH_REFUSALS' and paired['status']=='PASS_MATCHED_HAND_ADMISSION_COUNTERFACTUAL'
verdict='新姿态空手路径在本轮条件内通过；完整机器人与四臂真实任务安全尚未验收。' if status else '新姿态仍有中止或不合格路径，候选全面采用被拒绝；恢复成功不消除既有安全违规。'
admission=dict(admitted_requests=fresh['executed_requests'],qualified_requests=fresh['u_hand_paths'],abort_count=fresh['abort_count'],unknown_rejections=fresh['unknown_rejections'],unique_unknown_profiles=32,new_unknown_physical_paths=0)
links=[('独立样本分母与统计结论限制','STATISTICAL_SCOPE.md'),('四手观测包围盒，不能当作全操作空间','OBSERVED_HAND_ENVELOPES.json'),('验收矩阵：通过、失败、未执行分别列明','ACCEPTANCE_MATRIX.json'),('完整复现说明','FINAL_REPRODUCE.md'),('新姿态全部逐步评分、拒绝和恢复','VALIDATION_FRESH_V3_FULL_RESULTS.json'),('12个新姿态的事前注册与OS种子','REGISTRATION_VALIDATION_FRESH_V3.json'),('扩大验证协议','FRESH_EXTENDED_CONTRACT.md'),('V3机制与接触退回协议','SCENE_CONTACT_V3_CONTRACT.md'),('已知场景的回归结果','VALIDATION_V3_FULL_RESULTS.json'),('原目标拒绝与工装退回配对结果','PAIRED_V3_FULL_RESULTS.json'),('全部原始配对控制记录','paired_v3/admission_records.json'),('初始化失败V1完整结果','VALIDATION_FULL_RESULTS.json'),('V2逐点测量结果','VALIDATION_V2_FULL_RESULTS.json'),('V2外部接触失败诊断','VALIDATION_V2_EXTERNAL_DIAGNOSTIC.json'),('开发全部720路径结果','DEVELOPMENT_RESULTS.json'),('18个姿态的关节范围与未覆盖空间','COVERAGE_FINAL_REPORT.json'),('120档/118独特组合计数说明','COUNT_FIELD_NOTE.json'),('原生源快照与资产指纹','SOURCE_SNAPSHOT.json'),('完整媒体和逐步数据SHA清单','MEDIA_MANIFEST.json'),('8路视频原图绑定和编码记录','VIDEO_RECEIPT.json'),('新原生记录器','runtime_v3/native_fresh_extended_v3.py'),('外部接触和空手保护候选源码','runtime_v3/paths_v3.py'),('目标及姿态准入候选源码','runtime_v3/hand_admission.py'),('独立逐点力及目标审核器','analyze_v3.py'),('18项软件合同测试','ADMISSION_V3_SOFTWARE_TEST.log'),('初始化时期接触语义修复','BOOTSTRAP_FAILURE_CONTRACT.md'),('元数据键序漂移保留及修复','SOURCE_METADATA_DRIFT.json')]
camera=json.loads((root/'camera_replay_v2'/'recording_receipt.json').read_text())
for im in camera['images']:
 gallery.append(dict(run='camera_replay_v2',env=im['source_env'],method='fault_hold' if im['source_env']==6 else 'fault_recover',profile_index=1,time_s=im['source_native_state_time_s'],step=im['source_step'],images=[{**im,'file':'camera_replay_v2/'+im['file'],'view':'clear_detail','env':im['source_env'],'step':im['source_step']}]))
links.append(('遮挡修复：封存状态重渲染与连杆误差检查','CAMERA_REPLAY_NOTE.md'));links.append(('清晰视角重渲染注册与记录结构修复','REGISTRATION_CAMERA_REPLAY_V2.json'));links.append(('第一次重渲染错误保留','camera_replay/failure.txt'))
payload=dict(**data,observed_envelopes=json.loads((p/'OBSERVED_HAND_ENVELOPES.json').read_text()),phase_keys=['development','validation_v1','validation_v2','validation_v3','validation'],coverage=json.loads((p/'COVERAGE_FINAL_REPORT.json').read_text()),admission=admission,gallery=gallery,videos=json.loads((p/'VIDEO_RECEIPT.json').read_text())['videos'],verdict=verdict,links=[dict(label=l,file=f) for l,f in links],video_note='前四路为事前指定fresh/env0第一目标的四个视角；第5、6路为同初态旧目标直接执行/准入拒绝；第7、8路为工装保持/退回原生视频；第9、10路为同一工装存档状态的清晰视角重渲染，重渲染没有推进物理。同一时刻原生图像按10fps编码，60帧、6秒；退回组发生过接触仍判违规，拒绝组没有完成握持。无图像修饰。',curve_window_note='每12步取接触峰值，时间记为窗口结束；关节和目标取窗口最后一帧。完整逐步数据封存。')
(p/'DISPLAY_PAYLOAD.json.gz').write_bytes(gzip.compress(json.dumps(payload,separators=(',',':'),allow_nan=False).encode(),mtime=0));summary=dict(status='PASS_CONDITIONAL_HAND_CANDIDATE' if status else 'REJECT_CANDIDATE',verdict=verdict,development=data['development']['summary'],validation=fresh,regression=reg,paired=paired,historical_v1=data['validation_v1']['summary'],historical_v2=data['validation_v2']['summary'],admission=admission,new_task_trials=0,new_system0_trials=0,constructor_contacts_qualified=False,comprehensive_physical_safety_qualified=False,original_images=sum(len(g['images']) for g in gallery if g['run']!='camera_replay_v2'),reconstructed_images=len(camera['images']),native_env_states=sum(data[k]['summary']['env_states'] for k,_,_ in runs),fresh_reference_count=12,total_reference_count=18,videos=10,payload_sha256=sha(p/'DISPLAY_PAYLOAD.json.gz'))
(p/'SUMMARY.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(dict(status=summary['status'],states=summary['native_env_states'],images=summary['original_images'],fresh=fresh['executed_paths_qualified'],fresh_attempts=fresh['u_hand_paths']),indent=2))
