import argparse,json,hashlib,shutil
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--archive-commit',required=True);p.add_argument('--repo',type=Path,required=True);a=p.parse_args();root=Path(__file__).resolve().parent;summary=json.loads((root/'SUMMARY.json').read_text());doc=a.repo/'docs/safety_hand_closure_qualification_20261007';doc.mkdir(exist_ok=False)
base=f'https://raw.githubusercontent.com/asimfish/safeduo-dashboard/{a.archive_commit}/safety_hand_closure_qualification_20261007/'
(doc/'index.html').write_bytes((root/'panel.html').read_bytes());js=(root/'panel.js').read_text().replace('ARCHIVE_BASE',base).replace('PAYLOAD_SHA',summary['payload_sha256']);(doc/'panel.js').write_text(js)
(doc/'SUMMARY.json').write_bytes((root/'SUMMARY.json').read_bytes());archive=dict(commit=a.archive_commit,immutable_base=base,manifest_url=base+'MEDIA_MANIFEST.json',zip_url=f'https://codeload.github.com/asimfish/safeduo-dashboard/zip/{a.archive_commit}',download_verification='Every dataset manifest entry downloaded separately and compared to frozen bytes; whole history ZIP not independently downloaded in this delivery.');(doc/'MEDIA_ARCHIVE.json').write_text(json.dumps(archive,indent=2)+'\n')
manifest=[dict(file=f.name,bytes=f.stat().st_size,sha256=hashlib.sha256(f.read_bytes()).hexdigest()) for f in sorted(doc.iterdir())];(doc/'PUBLIC_MANIFEST.json').write_text(json.dumps(dict(files=manifest),indent=2)+'\n')
old=a.repo/'index.html';text=old.read_text();assert 'handClosureEvidence' not in text;(root/'ROOT_BEFORE.html').write_text(text)
d=summary['development'];v=summary['validation'];c=summary['paired'];card=f'''<section class="sci-note" id="handClosureEvidence"><h2>最新：手部全范围闭合与原生准入验收</h2><p>118个独特组合 / 120档：75网格、20纯随机、20分层随机及对照。三参考共360循环、720条U手路径（按伙伴向量合力评分，非逐点法向总量）；{d['profile_count_qualified']}/120档全部六条路径通过。拇指两关节覆盖完整限位，其他手指按固定比例耦合，不能算48手关节或26臂自由度独立随机。</p><p>事前规则选定{v['unique_profiles']}个精确目标，在三个新参考验证：{v['u_paths_qualified']}/{v['u_hand_paths']}条U手路径通过，新增逐点法向总量核验防止向量抵消；32未知随机目标拒绝，未作为物理安全样本计数。</p><p>同初态与相同旧目标对照：直接执行最大掌内自碰{c['bypass_max_scalar_self_normal_n']:.2f} N；准入拒绝组{c['guard_safe_paths']}/{c['guard_paths']}条保持开放，最大{c['guard_max_scalar_self_normal_n']:.2f} N。拒绝闭合没有完成握持，不能称任务成功或System0臂投影收益。</p><p>{summary['native_env_states']}个原生状态、{summary['original_images']}张原图、六路连续原生视频与全部失败可复核。完整夹持/释放、构造期接触、六臂对与全操作空间安全仍未完成。</p><p><a href="docs/safety_hand_closure_qualification_20261007/">查看完整网格、逐档曲线、配对安全效果、视频与验收 →</a></p></section>\n'''
anchor='<section class="sci-note" id="handInitializationEvidence">';assert anchor in text;text=text.replace(anchor,card+anchor,1);old.write_text(text);assert old.read_text().replace(card,'',1)==(root/'ROOT_BEFORE.html').read_text()
print('MAIN_ADD_BYTES',sum(f.stat().st_size for f in doc.iterdir())+len(card.encode()))
