from pathlib import Path
import json,subprocess,hashlib,shutil
p=Path(__file__).resolve().parent;raw=Path('/mnt/nas/data/lyf/double_hand/safety_hand_closure_qualification_20261007');out=p/'videos';out.mkdir(exist_ok=False);videos=[];sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
for run,env,view,label in [('validation_fresh_v3',0,v,'新抽取姿态 · '+v) for v in ['top','front','side','detail']]+[('paired_v3',e,'detail',l) for e,l in [(0,'原旧目标直接执行'),(1,'原旧目标准入拒绝'),(6,'工装接触后保持目标'),(7,'工装接触后空手退回')]]:
 receipt=json.loads((raw/run/'recording_receipt.json').read_text());frames=sorted([x for x in receipt['images'] if x['env']==env and x['view']==view and x['step']<720 and x['step']%12==0],key=lambda x:x['step']);assert len(frames)==60;assert [x['step'] for x in frames]==list(range(0,720,12));tag=f'{run}_e{env}_{view}';lst=out/(tag+'.txt');lst.write_text(''.join("file '"+str(raw/run/x['file'])+"'\nduration 0.1\n" for x in frames))
 for ext,codec in [('mp4',['-c:v','libx264','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart']),('webm',['-c:v','libvpx-vp9','-crf','30','-b:v','0','-row-mt','1'])]:
  dst=out/(tag+'.'+ext);subprocess.run(['ffmpeg','-hide_banner','-loglevel','error','-f','concat','-safe','0','-i',str(lst),'-frames:v','60','-r','10','-threads','2',*codec,str(dst)],check=True)
  info=json.loads(subprocess.check_output(['ffprobe','-v','error','-count_frames','-select_streams','v:0','-show_entries','stream=width,height,nb_read_frames,avg_frame_rate,duration','-of','json',str(dst)]))['streams'][0];assert int(info['nb_read_frames'])==60 and info['width']==1280 and info['height']==720
 videos.append(dict(run=run,env=env,view=label,frames=60,fps=10,mp4='videos/'+tag+'.mp4',webm='videos/'+tag+'.webm',poster=run+'/'+frames[0]['file'],mp4_sha256=sha(out/(tag+'.mp4')),webm_sha256=sha(out/(tag+'.webm')),source_frames=[dict(file=run+'/'+x['file'],sha256=x['sha256'],step=x['step'],native_state_time_s=x['state_time_s']) for x in frames],decode=info));print('ENCODED',tag,flush=True)
(p/'VIDEO_RECEIPT.json').write_text(json.dumps(dict(status='PASS_ORIGINAL_NATIVE_FRAMES_8_VIDEOS_TWO_CODECS',videos=videos,retouched=False),indent=2)+'\n')
