const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let D;
const fmt=(v,n=4)=>Number(v).toFixed(n);
function render(){const e=Number($('#case').value),a=$('#arm').value,k=$('#metric').value,c=D.cases[e];
 const series=D.series[e][a],col=['#8dbaff','#ffbd70'];let ymax=k==='contact'?1:.23;
 for(const v of Object.values(series))ymax=Math.max(ymax,...v[k]);ymax*=1.12;
 const x=t=>65+t/12*865,y=v=>255-v/ymax*210;
 let html='<g fill="#b2c1d9" font-size="13">';for(let i=0;i<=4;i++){let v=ymax*i/4;html+=`<path d="M65 ${y(v)}H930" stroke="#33435e"/><text x="6" y="${y(v)+4}">${fmt(v,2)}</text>`;}for(let t=0;t<=12;t+=2)html+=`<text x="${x(t)-5}" y="279">${t}</text>`;
 html+='<text x="725" y="300">物理时间（秒）</text></g>';
 if(k==='error')html+=`<path d="M65 ${y(.2)}H930" stroke="#e77474" stroke-dasharray="6 4"/><text x="75" y="${y(.2)-5}" fill="#e77474" font-size="13">旧判据0.2rad</text>`;
 ['baseline_v2','self_off_v2'].forEach((name,i)=>{const v=series[name];html+=`<polyline fill="none" stroke="${col[i]}" stroke-width="2" points="${v.time.map((t,j)=>`${x(t)},${y(v[k][j])}`).join(' ')}"/>`;html+=`<text x="${70+i*245}" y="25" fill="${col[i]}" font-size="15">${i===0?'保留自碰':'关闭自碰（仅诊断）'}</text>`;});$('#chart').innerHTML=html;
 $('#chart-note').textContent=`${c.label_cn} · ${a}。曲线每6物理步显示一次，完整1440步在归档。物理步0.008333秒；最后状态与原图单独绑定。`;
 $('#hands').innerHTML=D.results.baseline_v2.cases[e].hands.map((b,i)=>{let f=D.results.self_off_v2.cases[e].hands[i],w=b.windows.returned_open,fw=f.windows.returned_open;return `<tr><td>${b.arm}</td><td>${fmt(b.windows.initial_open.max_error_to_default_rad)}</td><td>${fmt(w.max_error_to_default_rad)}</td><td>${fmt(fw.max_error_to_default_rad)}</td><td>${w.default_open_states}/${w.states} / ${fw.default_open_states}/${fw.states}</td></tr>`;}).join('');gallery();}
function gallery(){const e=Number($('#case').value),cond=$('#condition').value,step=Number($('#frame').value);let imgs=D.images.filter(v=>v.condition===cond&&v.env===e&&v.step===step);$('#gallery').innerHTML=imgs.map(v=>`<figure><a href="${esc(v.url)}" target="_blank" rel="noopener"><img src="${esc(v.url)}" alt="${esc(v.view)}原始图，环境${e}，步骤${step}" loading="lazy"></a><figcaption>${esc(v.view)} · ${fmt(v.state_time_s,3)}秒</figcaption></figure>`).join('');$('#image-note').textContent=`${D.cases[e].label_cn} · ${cond==='baseline_v2'?'保留自碰':'关闭自碰（仅诊断）'} · 步骤${step}，三张对应同一物理状态。`;}
function openingGallery(){const pose=Number($('#opening-case').value),method=$('#opening-method').value,step=Number($('#opening-step').value);const c=D.opening_pose.cases.find(c=>Math.floor(c.env/2)===pose&&c.method===method);$('#opening-gallery').innerHTML=D.opening_images.filter(i=>i.env===c.env&&i.step===step).map(i=>`<figure><a href="${esc(i.url)}" target="_blank" rel="noopener"><img src="${esc(i.url)}" alt="开放姿态对照${c.env} ${esc(i.view)} 步骤${step}" loading="lazy"></a><figcaption>${esc(i.view)} · ${fmt(i.state_time_s,3)}秒</figcaption></figure>`).join('');}
function opening(){const o=D.opening_pose;$('#opening-verdict').textContent=`提议开放目标通过静态验收 ${o.candidate_accepted}/${o.candidate_cases}；原零目标 ${o.baseline_accepted}/${o.baseline_cases}。手部净力与全部伙伴法向重建最大差 ${o.max_hand_net_filter_accounting_abs_n.toExponential(2)}N。只用于此开放信号资格，未验证任务抓持。`;let rows=[];const labels=['初始','取物','放置','退离'];for(let i=0;i<4;i++){const b=o.cases[i*2],c=o.cases[i*2+1];for(let j=2;j<4;j++){let bh=b.hands[j],ch=c.hands[j];rows.push(`<tr><td>${labels[i]} / ${ch.arm}</td><td>${fmt(bh.max_error_to_reference_rad)}</td><td>${fmt(ch.max_error_to_reference_rad)}</td><td>${fmt(bh.max_each_pair_normal_n,3)}</td><td>${fmt(ch.max_each_pair_normal_n,3)}</td><td>${ch.accepted_static_opening?'通过':'未通过'}</td></tr>`);}}$('#opening-hands').innerHTML=rows.join('');$('#opening-case').innerHTML=labels.map((l,i)=>`<option value="${i}">${l}</option>`).join('');$('#opening-step').value='1199';['#opening-case','#opening-method','#opening-step'].forEach(s=>$(s).addEventListener('change',openingGallery));openingGallery();}
async function init(){D=await(await fetch('data.json')).json();$('#verdict').innerHTML=D.verdict.map(v=>`<p>${esc(v)}</p>`).join('');$('#case').innerHTML=D.cases.map(v=>`<option value="${v.env}">${esc(v.label_cn)}</option>`).join('');$('#arm').innerHTML=['F_L','F_R','U_L','U_R'].map(a=>`<option>${a}</option>`).join('');$('#arm').value='U_R';$('#frame').innerHTML=D.capture_steps.map(v=>`<option value="${v}">${fmt((v+1)*.008333,3)}秒</option>`).join('');$('#frame').value=String(D.capture_steps.at(-1));
 const m=D.results.baseline_v2.measurement;$('#measurement').textContent=`碰撞几何${m.collision_shapes}项，其中实例代理${m.instance_proxy_collision_shapes}项；互不重叠伙伴${m.partner_count_env0}项。法向重建最大误差${m.normal_reconstruction_max_abs_n.toExponential(2)}N；净力与全部过滤法向最大差${m.net_minus_filtered_normal_max_abs_n.toExponential(2)}N。静态支撑重量资格：${m.static_support_weight_qualified?'通过':'未通过'}。`;
 $('#support').innerHTML=D.results.baseline_v2.support.map(v=>`<tr><td>${esc(D.cases[v.env].label_cn)} / ${v.object}</td><td>${fmt(v.weight_n,3)}</td><td>${fmt(v.table_only_support_weight_fraction*100,1)}%</td><td>${fmt(v.mean_net_contact_n[2],3)}</td><td>${v.net_minus_normal_sum_max_abs_n.toExponential(2)}</td></tr>`).join('');
 $('#components').innerHTML=D.results.baseline_v2.support.map(v=>`<details><summary>${esc(D.cases[v.env].label_cn)} / ${v.object}：实际受力伙伴</summary>${v.components.map(p=>`<p class="small"><code>${esc(p.path.split('/env_'+v.env+'/').at(-1))}</code> · 平均法向Z ${fmt(p.mean_normal_force_n[2],4)}N · 平均摩擦Z ${fmt(p.mean_friction_force_n[2],4)}N</p>`).join('')}</details>`).join('');
 $('#links').innerHTML=D.links.map(v=>`<a href="${esc(v.url)}">${esc(v.label)}</a>`).join('');$('#archive-note').textContent=`固定原始归档提交 ${D.archive.commit}；${D.archive.files}个原始文件，${fmt(D.archive.bytes/1024/1024,2)}MiB。所有文件下载后按SHA复核。`;
 ['#case','#arm','#metric'].forEach(s=>$(s).addEventListener('change',render));['#condition','#frame'].forEach(s=>$(s).addEventListener('change',gallery));opening();render();}
init().catch(e=>{$('#error').textContent='数据加载失败：'+e.message;console.error(e);});
